config:
  aws:region: us-east-1
  nextjs-apprunner:app-name: nextjs-app
  nextjs-apprunner:cpu: "512"
  nextjs-apprunner:memory: "1024"
  nextjs-apprunner:app-port: "3000"
  nextjs-apprunner:max-concurrency: "100"
  nextjs-apprunner:max-size: "2"
  nextjs-apprunner:min-size: "1"
  nextjs-apprunner:billing-id: "test-nextjs-apprunner"
